language: python
sudo: false
env:
  - RUNCOVERAGE=1
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pytest coverage header2whatever
  - python setup.py sdist
  - "pip install dist/robotpy-ctre-*.tar.gz"
# command to run tests
script:
  - tests/run_tests.sh
  
  # TODO
  #- pip uninstall robotpy-hal-sim
  #- pip install robotpy-hal-roborio
  #- TRAVIS_BUILD=1 python setup.py build
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
